# Generated by Django 5.2.12 on 2026-04-06 00:58

import django.db.models.deletion
import django.utils.timezone
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("user.login", "User login"),
                            ("user.logout", "User logout"),
                            ("user.login_failed", "User login failed"),
                            ("user.locked_out", "User locked out"),
                            ("user.created", "User created"),
                            ("user.disabled", "User disabled"),
                            ("user.enabled", "User enabled"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("actor_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user", "User"),
                            ("agent", "Agent"),
                            ("scope_item", "Scope Item"),
                        ],
                        default="",
                        max_length=64,
                    ),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "target_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["actor_user", "-timestamp"],
                        name="audit_audit_actor_u_893c19_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id", "-timestamp"],
                        name="audit_audit_target__96bd16_idx",
                    ),
                ],
            },
        ),
    ]
