# Generated by Django 5.2.12 on 2026-04-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("user.login", "User login"),
                    ("user.logout", "User logout"),
                    ("user.login_failed", "User login failed"),
                    ("user.locked_out", "User locked out"),
                    ("ip.locked_out", "IP locked out"),
                    ("user.created", "User created"),
                    ("user.disabled", "User disabled"),
                    ("user.enabled", "User enabled"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
