version: "2"
plugins:
  pep8:
    enabled: true
    checks:
      E261:
        enabled: false
      E402:
        enabled: false
      W191:
        enabled: false
      E117:
        enabled: false
  radon:
    enabled: true
    config:
      python_version: 3
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true
  stylelint:
    enabled: true
