##################################
#      DEVELOPMENT USE ONLY      #
# DO NOT USE THIS IN PRODUCTION! #
##################################
version: "3.7"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elastic
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend

  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=natlas-dev-password-do-not-use
      - MYSQL_DATABASE=natlas
    networks:
      - backend

  zipkin-server:
    image: openzipkin/zipkin-slim:2.21.6
    ports:
      - 9411:9411
    networks:
      - backend

  opencensus-agent:
    image: omnition/opencensus-agent:0.1.11
    command: --config=/conf/opencensus-dev.yml
    volumes:
      - ./.opencensus-dev.yml:/conf/opencensus-dev.yml:ro
    networks:
      - backend

  webpack-server:
    image: node:14-stretch
    command: /bin/bash -c '/usr/local/bin/yarn install && /usr/local/bin/yarn run webpack --mode development --watch'
    networks:
      - backend
    volumes:
      - ./natlas-server:/app
      - node_modules:/app/node_modules
      - html_assets:/app/static/dist
    working_dir: /app

  natlas-server:
    build: natlas-server
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    networks:
      - backend
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - FLASK_ENV=development
      - OPENCENSUS_AGENT=opencensus-agent:55678
    volumes:
      - ns-data:/data
      - ./natlas-server:/opt/natlas/natlas-server
      - html_assets:/opt/natlas/natlas-server/static/dist
    links:
      - elastic

  natlas-agent:
    build: natlas-agent
    networks:
      - backend
    environment:
      - NATLAS_SERVER_ADDRESS=http://natlas-server:5000
      - NATLAS_SCAN_LOCAL=true
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp=./natlas-agent/chrome.json
    volumes:
      - ./natlas-agent:/opt/natlas/natlas-agent
    links:
      - natlas-server

networks:
  backend:

volumes:
  ns-data:
  elastic:
  node_modules:
  html_assets:
