[dependency-groups]
dev = [
  "django-debug-toolbar~=5.0",
  "django-stubs[compatible-mypy]~=5.2",
  "mypy~=1.14",
  "pytest-cov~=6.0",
  "pytest-django~=4.10",
  "pytest~=8.3"
]

[project]
dependencies = [
  "celery[redis]~=5.6",
  "django-anymail~=14.0",
  "django-celery-beat~=2.7",
  "django-cotton~=2.6",
  "django-netfields~=1.3",
  "django-ninja~=1.3",
  "django-stubs-ext~=5.2",
  "django-waffle~=5.0",
  "djangoql~=0.18",
  "django~=5.2",
  "gunicorn~=25.0",
  "opentelemetry-exporter-otlp-proto-grpc~=1.27",
  "opentelemetry-instrumentation-celery~=0.48b0",
  "opentelemetry-instrumentation-django~=0.48b0",
  "opentelemetry-instrumentation-psycopg~=0.48b0",
  "opentelemetry-instrumentation-redis~=0.48b0",
  "opentelemetry-sdk~=1.27",
  "psycopg[binary]~=3.2",
  "sentry-sdk[django]~=2.0",
  "uuid6~=2025.0"
]
name = "natlas"
requires-python = ">=3.13"
version = "0.6.12"

[tool.coverage.report]
show_missing = true
skip_covered = false

[tool.coverage.run]
omit = [
  "*/migrations/*",
  "*/tests/*"
]
source = ["apps", "config"]

[tool.django-stubs]
django_settings_module = "config.settings"

[tool.mypy]
disable_error_code = [
  "import-untyped",
  "no-untyped-call"
]
enable_error_code = [
  "ignore-without-code",
  "possibly-undefined",
  "redundant-self",
  "truthy-bool",
  "truthy-iterable",
  "unimported-reveal",
  "unused-awaitable"
]
exclude = [
  'apps/.*/migrations/.*\.py$'
]
files = [
  "apps",
  "config",
  "manage.py"
]
local_partial_types = true
no_implicit_reexport = true
plugins = [
  "mypy_django_plugin.main"
]
pretty = false
strict = true
strict_optional = true
warn_unreachable = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
addopts = "--cov=apps --cov=config --cov-report=term-missing --cov-report=html"

[tool.ruff]

[tool.ruff.lint]
ignore = [
  "PLC0414",
  "PLR0911",
  "PLR0912",
  "PLR0915",
  "PLR2004",
  # TODO: audit all mutable ClassVar annotations and re-enable
  "RUF012"
]
select = [
  # flake8-bugbear
  "B",
  # flake8-comprehensions
  "C4",
  # pyflakes
  "F",
  # flynt
  "FLY",
  # isort
  "I",
  # pylint
  "PL",
  # flake8-return
  "RET",
  # Ruff's own rules
  "RUF",
  # flake8-simplify
  "SIM",
  # flake8-tidy-imports
  "TID",
  # pyupgrade
  "UP"
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.per-file-ignores]
"natlas-agent/**" = ["PLC0415", "RUF059", "UP047"]
"natlas-server/**" = ["PLC0415", "RUF059", "UP047"]

[tool.uv]
package = false
