# Generated by Django 5.2.12 on 2026-03-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("natlas", "0005_scancycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="scantask",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="natlas.scancycle",
            ),
        ),
    ]
