# Generated by Django 5.2.12 on 2026-03-08 20:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("natlas", "0007_latestscanresult_scan_result_port_script_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="raw_nmap",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="scanresult",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "raw_nmap", config="english"
                ),
                name="scanresult_raw_nmap_fts_idx",
            ),
        ),
    ]
