# Generated by Django 5.2.12 on 2026-03-06 07:08

import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScopeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target",
                    netfields.fields.CidrAddressField(max_length=43, unique=True),
                ),
                ("is_blocked", models.BooleanField(db_index=True, default=False)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="scope_items", to="natlas.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["target"],
            },
        ),
    ]
