# Generated by Django 5.2.12 on 2026-03-14 21:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import netfields.fields
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("token_hash", models.CharField(max_length=256)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DNSRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=253)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("AAAA", "AAAA"),
                            ("CNAME", "CNAME"),
                            ("PTR", "PTR"),
                            ("MX", "MX"),
                            ("NS", "NS"),
                            ("TXT", "TXT"),
                        ],
                        max_length=5,
                    ),
                ),
                ("value", models.CharField(max_length=253)),
                (
                    "resolved_ip",
                    netfields.fields.InetAddressField(
                        blank=True, db_index=True, max_length=39, null=True
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "record_type", "value"),
                        name="unique_dns_record",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScanCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("complete", "Complete"),
                            ("interrupted", "Interrupted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("scope_snapshot", models.JSONField()),
                ("total_ips", models.PositiveBigIntegerField()),
                ("ips_queued", models.PositiveBigIntegerField(default=0)),
                ("lcg_m", models.BigIntegerField()),
                ("lcg_a", models.BigIntegerField()),
                ("lcg_b", models.BigIntegerField()),
                ("lcg_current", models.BigIntegerField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("status",),
                        name="unique_active_scan_cycle",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target",
                    netfields.fields.InetAddressField(db_index=True, max_length=39),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("scan_start", models.DateTimeField(db_index=True)),
                ("scan_stop", models.DateTimeField(db_index=True)),
                ("raw_data", models.JSONField()),
                ("raw_nmap", models.TextField(blank=True, default="")),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_results",
                        to="natlas.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port_number", models.IntegerField()),
                (
                    "protocol",
                    models.CharField(
                        choices=[("tcp", "TCP"), ("udp", "UDP")], max_length=3
                    ),
                ),
                ("state", models.CharField(max_length=10)),
                (
                    "service_name",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "service_product",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "service_version",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "service_extra",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "scan_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports",
                        to="natlas.scanresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScanTask",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target", netfields.fields.InetAddressField(max_length=39)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("claim_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_tasks",
                        to="natlas.agent",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="natlas.scancycle",
                    ),
                ),
                (
                    "scan_result",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_task",
                        to="natlas.scanresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=64)),
                ("output", models.TextField()),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scripts",
                        to="natlas.port",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScopeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target",
                    netfields.fields.CidrAddressField(max_length=43, unique=True),
                ),
                ("is_blocked", models.BooleanField(db_index=True, default=False)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="scope_items", to="natlas.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["target"],
            },
        ),
        migrations.AddIndex(
            model_name="scanresult",
            index=models.Index(
                fields=["target", "scanned_at"], name="natlas_scan_target_772cac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanresult",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "raw_nmap", config="english"
                ),
                name="scanresult_raw_nmap_fts_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="port",
            index=models.Index(
                fields=["port_number"], name="natlas_port_port_nu_5e5577_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="port",
            index=models.Index(
                fields=["service_name"], name="natlas_port_service_646010_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="port",
            constraint=models.UniqueConstraint(
                fields=("scan_result", "port_number", "protocol"),
                name="unique_port_per_scan",
            ),
        ),
        migrations.AddIndex(
            model_name="scantask",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["status"],
                name="idx_scan_task_pending",
            ),
        ),
        migrations.AddConstraint(
            model_name="scantask",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "claimed"])),
                fields=("target",),
                name="unique_active_scan_task_per_target",
            ),
        ),
    ]
