# Generated by Django 5.2.12 on 2026-04-02 04:16

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("natlas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSLCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fingerprint_sha1", models.CharField(max_length=40, unique=True)),
                (
                    "subject_cn",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("subject", models.JSONField(default=dict)),
                ("issuer_cn", models.CharField(blank=True, default="", max_length=256)),
                ("issuer", models.JSONField(default=dict)),
                ("not_valid_before", models.DateTimeField(blank=True, null=True)),
                ("not_valid_after", models.DateTimeField(blank=True, null=True)),
                (
                    "public_key_type",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("public_key_bits", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "subject_alt_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=253),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("pem", models.TextField(blank=True, default="")),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "ports",
                    models.ManyToManyField(
                        blank=True, related_name="certificates", to="natlas.port"
                    ),
                ),
            ],
            options={
                "verbose_name": "SSL Certificate",
                "verbose_name_plural": "SSL Certificates",
                "indexes": [
                    models.Index(
                        fields=["subject_cn"], name="natlas_sslc_subject_0cb4e7_idx"
                    ),
                    models.Index(
                        fields=["not_valid_after"],
                        name="natlas_sslc_not_val_63fe06_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["subject_alt_names"], name="sslcert_sans_gin_idx"
                    ),
                ],
            },
        ),
    ]
