# Generated by Django 5.2.12 on 2026-04-02 04:33

import django.contrib.postgres.indexes
import django.db.models.expressions
from django.db import migrations, models

CREATE_REVERSE_LABELS = """
CREATE OR REPLACE FUNCTION reverse_labels(input text)
RETURNS text
LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $$
    SELECT array_to_string(array_reverse(string_to_array(input, '.')), '.')
$$;
"""

DROP_REVERSE_LABELS = "DROP FUNCTION IF EXISTS reverse_labels(text);"


class Migration(migrations.Migration):
    dependencies = [
        ("natlas", "0002_sslcertificate"),
    ]

    operations = [
        migrations.RunSQL(CREATE_REVERSE_LABELS, reverse_sql=DROP_REVERSE_LABELS),
        migrations.AddField(
            model_name="dnsrecord",
            name="name_reversed",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.RawSQL(
                    "reverse_labels(name)",
                    output_field=models.CharField(max_length=253),
                    params=[],
                ),
                output_field=models.CharField(max_length=253),
            ),
        ),
        migrations.AlterField(
            model_name="dnsrecord",
            name="name",
            field=models.CharField(max_length=253),
        ),
        migrations.AddIndex(
            model_name="dnsrecord",
            index=models.Index(
                django.contrib.postgres.indexes.OpClass(
                    "name", name="varchar_pattern_ops"
                ),
                name="dnsrecord_name_prefix_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dnsrecord",
            index=models.Index(
                django.contrib.postgres.indexes.OpClass(
                    "name_reversed", name="varchar_pattern_ops"
                ),
                name="dnsrecord_name_rev_prefix_idx",
            ),
        ),
    ]
