# Generated by Django 5.2.12 on 2026-03-07 00:30

import django.db.models.deletion
import django.utils.timezone
import netfields.fields
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("natlas", "0002_agent_scopeitem_created_at_scopeitem_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.UUIDField(default=uuid6.uuid7)),
                (
                    "target",
                    netfields.fields.InetAddressField(db_index=True, max_length=39),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("raw_data", models.JSONField()),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to="natlas.agent",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target",), name="unique_latest_scan_result_target"
                    ),
                    models.UniqueConstraint(
                        fields=("scan_id",), name="unique_latest_scan_result_scan_id"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_id", models.UUIDField(default=uuid6.uuid7)),
                (
                    "target",
                    netfields.fields.InetAddressField(db_index=True, max_length=39),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("raw_data", models.JSONField()),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to="natlas.agent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target", "scanned_at"],
                        name="natlas_scan_target_772cac_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scan_id",), name="unique_scan_result_scan_id"
                    )
                ],
            },
        ),
    ]
