# Generated by Django 5.2.12 on 2026-03-07 00:41

import django.db.models.deletion
import django.utils.timezone
import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("natlas", "0003_latestscanresult_scanresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target", netfields.fields.InetAddressField(max_length=39)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("claim_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_tasks",
                        to="natlas.agent",
                    ),
                ),
                (
                    "scan_result",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scan_task",
                        to="natlas.scanresult",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("status", "pending")),
                        fields=["status"],
                        name="idx_scan_task_pending",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ["pending", "claimed"])),
                        fields=("target",),
                        name="unique_active_scan_task_per_target",
                    )
                ],
            },
        ),
    ]
