# Generated by Django 5.2.12 on 2026-03-07 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("natlas", "0004_scantask"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("complete", "Complete"),
                            ("interrupted", "Interrupted"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("scope_snapshot", models.JSONField()),
                ("total_ips", models.BigIntegerField()),
                ("ips_queued", models.BigIntegerField(default=0)),
                ("lcg_m", models.BigIntegerField()),
                ("lcg_a", models.BigIntegerField()),
                ("lcg_b", models.BigIntegerField()),
                ("lcg_current", models.BigIntegerField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("status",),
                        name="unique_active_scan_cycle",
                    )
                ],
            },
        ),
    ]
