# Generated by Django 5.2.12 on 2026-04-06 01:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("natlas", "0004_scanresult_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("system_default", "System Default"),
                            ("user_default", "User Default"),
                            ("named", "Named"),
                        ],
                        db_index=True,
                        default="named",
                        max_length=32,
                    ),
                ),
                (
                    "enabled_plugins",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        blank=True,
                        default=list,
                        help_text="List of plugin names to run. Each plugin must be explicitly enabled.",
                        size=None,
                    ),
                ),
                ("nmap_config", models.JSONField(blank=True, default=dict)),
                ("nuclei_config", models.JSONField(blank=True, default=dict)),
                ("screenshot_config", models.JSONField(blank=True, default=dict)),
                ("whatweb_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("tier", "system_default")),
                        fields=("tier",),
                        name="unique_system_default",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("tier", "user_default")),
                        fields=("tier",),
                        name="unique_user_default",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="scan_config",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agents",
                to="natlas.scanconfig",
            ),
        ),
    ]
