# Generated by Django 5.2.12 on 2026-03-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("natlas", "0008_scanresult_raw_nmap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="latestscanresult",
            name="scan_start",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="latestscanresult",
            name="scan_stop",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="scan_start",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="scanresult",
            name="scan_stop",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
